# TPOT

In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.pipeline import make_pipeline, make_union
from sklearn.preprocessing import Normalizer
from tpot.builtins import StackingEstimator
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score

## Workout Types

### df_gym_IQR

Best pipeline: MultinomialNB(Normalizer(GaussianNB(input_matrix), norm=l2), alpha=1.0, fit_prior=True)

In [7]:
# NOTE: Make sure that the outcome column is labeled 'target' in the data file
tpot_data = pd.read_csv('../data/gym_members_exercise_tracking.csv') # pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR', dtype=np.float64)
tpot_data = tpot_data.replace({
    "Yoga" : 0,
    "HIIT" : 1,
    "Cardio" : 2,
    "Strength" : 3,
    "Female" : 0,
    "Male": 0
    })

display(tpot_data.info())

features = tpot_data.drop('Workout_Type', axis=1)
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['Workout_Type'], random_state=None)

# Average CV score on the training set was: 0.28896197327852
exported_pipeline = make_pipeline(
    StackingEstimator(estimator=GaussianNB()),
    Normalizer(norm="l2"),
    MultinomialNB(alpha=1.0, fit_prior=True)
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Age                            973 non-null    int64  
 1   Gender                         973 non-null    int64  
 2   Weight (kg)                    973 non-null    float64
 3   Height (m)                     973 non-null    float64
 4   Max_BPM                        973 non-null    int64  
 5   Avg_BPM                        973 non-null    int64  
 6   Resting_BPM                    973 non-null    int64  
 7   Session_Duration (hours)       973 non-null    float64
 8   Calories_Burned                973 non-null    float64
 9   Workout_Type                   973 non-null    int64  
 10  Fat_Percentage                 973 non-null    float64
 11  Water_Intake (liters)          973 non-null    float64
 12  Workout_Frequency (days/week)  973 non-null    int

/var/folders/4j/v1g8gthx209g90f63vh1krc80000gn/T/ipykernel_42590/3802289015.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tpot_data = tpot_data.replace({


None

/Users/clarapichler/Documents/Projects/myenv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/Users/clarapichler/Documents/Projects/myenv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/Users/clarapichler/Documents/Projects/myenv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/Users/clarapichler/Documents/Projects/myenv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [10]:
accuracy = accuracy_score(testing_target, results)
print('Model Performance')
print('Accuracy = {:0.2f}%.'.format(accuracy * 100))
print('Classification Report:')
print(classification_report(testing_target, results, zero_division=1))
print('Confusion Matrix:')
print(confusion_matrix(testing_target, results))

Model Performance
Accuracy = 29.51%.
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.00      0.00        58
           1       1.00      0.00      0.00        54
           2       0.36      0.12      0.18        65
           3       0.29      0.96      0.44        67

    accuracy                           0.30       244
   macro avg       0.66      0.27      0.16       244
weighted avg       0.64      0.30      0.17       244

Confusion Matrix:
[[ 0  0  8 50]
 [ 0  0  3 51]
 [ 0  0  8 57]
 [ 0  0  3 64]]


## Calories Burned

### df_cal_IQR